# Generated by Django 5.2.3 on 2025-06-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
