# Generated by Django 5.2.3 on 2025-06-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_app', '0003_alter_record_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
