# Generated by Django 5.2.3 on 2025-06-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_app', '0005_alter_record_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
